"""Non-Cartesian encoding preparation and, later, NUFFT backends."""

from xcat_icmr.encoding.inputs import (
    EncodingInputError,
    LogicalInputPreview,
    PreparedContrast,
    center_padding,
    format_prepared_contrast,
    format_logical_input_preview,
    prepare_contrast_for_encoding,
    save_logical_input_preview,
)
from xcat_icmr.encoding.diagnostics import (
    FovCandidateDiagnostic,
    FovPsfDiagnostic,
    SignalSupport,
    format_fov_psf_diagnostic,
    matrix_shape_for_fov,
    measure_centered_signal_support,
    run_fov_psf_diagnostic,
)
from xcat_icmr.encoding.comparison import (
    DeviceParity,
    ImageReferenceValidation,
    compare_device_references,
    validate_image_reference,
)
from xcat_icmr.encoding.sigpy_backend import (
    DEFAULT_NUFFT_KERNEL_WIDTH,
    DEFAULT_NUFFT_OVERSAMPLING,
    NufftBackendError,
    SigpyNufftBackend,
)
from xcat_icmr.encoding.trajectory import (
    EncodingGrids,
    EncodingTrajectory,
    TrajectoryPreparationError,
    format_encoding_trajectory,
    prepare_encoding_grids,
    prepare_physical_sigpy_trajectory,
    prepare_sigpy_trajectory,
    scale_isotropic_trajectory_to_resolution,
)
from xcat_icmr.encoding.validation import (
    MulticoilFrameEncoding,
    MulticoilNufftDebug,
    ReducedNufftValidation,
    SigpyReferenceValidation,
    circular_shift_to_rf_center,
    encode_multicoil_frame,
    format_multicoil_nufft_debug,
    format_reduced_nufft_validation,
    format_sigpy_reference_validation,
    run_reduced_nufft_validation,
    run_multicoil_nufft_debug,
    validate_sigpy_reference,
)

__all__ = [
    "EncodingInputError",
    "DEFAULT_NUFFT_KERNEL_WIDTH",
    "DEFAULT_NUFFT_OVERSAMPLING",
    "DeviceParity",
    "ImageReferenceValidation",
    "LogicalInputPreview",
    "MulticoilNufftDebug",
    "MulticoilFrameEncoding",
    "EncodingGrids",
    "EncodingTrajectory",
    "FovCandidateDiagnostic",
    "FovPsfDiagnostic",
    "NufftBackendError",
    "PreparedContrast",
    "ReducedNufftValidation",
    "SigpyNufftBackend",
    "SigpyReferenceValidation",
    "SignalSupport",
    "TrajectoryPreparationError",
    "center_padding",
    "circular_shift_to_rf_center",
    "compare_device_references",
    "encode_multicoil_frame",
    "format_prepared_contrast",
    "format_logical_input_preview",
    "format_multicoil_nufft_debug",
    "format_encoding_trajectory",
    "format_fov_psf_diagnostic",
    "format_reduced_nufft_validation",
    "format_sigpy_reference_validation",
    "prepare_contrast_for_encoding",
    "save_logical_input_preview",
    "prepare_encoding_grids",
    "prepare_physical_sigpy_trajectory",
    "prepare_sigpy_trajectory",
    "scale_isotropic_trajectory_to_resolution",
    "matrix_shape_for_fov",
    "measure_centered_signal_support",
    "run_fov_psf_diagnostic",
    "run_reduced_nufft_validation",
    "run_multicoil_nufft_debug",
    "validate_sigpy_reference",
    "validate_image_reference",
]
